### ISSUE TITLE
appends when executed multiple times

### ISSUE THREAD

**Issue by DanielRuf** [clue/phar-composer#100]
It seems when I run it locally multiple times it appends the same content to the same phar.

```
➜  Project git:(master) ✗ php -d phar.readonly=off ./tools/phar-composer.phar build .
[1/1] Creating phar project.phar
  - Adding main package "eftec/project"
  - Adding composer base files
  - Setting main/stub
    Using referenced chmod 0644
    Applying chmod 0644
  - Overwriting existing file project.phar (5470.5 KiB)

    OK - Creating project.phar (10941.1 KiB) completed after 1s
➜  Project git:(master) ✗ php -d phar.readonly=off ./tools/phar-composer.phar build .
[1/1] Creating phar project.phar
  - Adding main package "eftec/project"
  - Adding composer base files
  - Setting main/stub
    Using referenced chmod 0644
    Applying chmod 0644
  - Overwriting existing file project.phar (10941.1 KiB)

    OK - Creating project.phar (16411.7 KiB) completed after 1.1s
➜  Project git:(master) ✗ php -d phar.readonly=off ./tools/phar-composer.phar build .
[1/1] Creating phar project.phar
  - Adding main package "eftec/project"
  - Adding composer base files
  - Setting main/stub
    Using referenced chmod 0644
    Applying chmod 0644
  - Overwriting existing file project.phar (16411.7 KiB)

    OK - Creating project.phar (21882.3 KiB) completed after 1.4s
```

**Comment by DanielRuf** [comment]
> Overwriting existing file project.phar

So it is not overwritten? At least it also seems the `bin`entry is not used only once.

**Comment by clue** [comment]
@DanielRuf Thanks for reporting!

I understand where you're coming from and agree that this looks *strange* to say the least, but this is indeed expected behavior at the moment:

When running phar-composer, it will bundle *all* files from the local directory, i.e. it will include your existing `project.phar` into your new `project.phar` which causes the archive to grow on each run.

At the moment, this can be prevented by running this in a temporary build directory like #91. We will also likely add an option to ignore certain files via #5. I'm open for more input :+1:

**Comment by DanielRuf** [comment]
Hi @clue,

thanks for the feedback. I really appreciate the time that you invest into this and the other projects. I switched to the maintained box fork as this brought many improvements and worked for my needs.

I will revisit #91 in the next weeks and try this approach. Thanks for the links. I was already aware of #5 but I was not aware of #91 =)
