### ISSUE TITLE
Something is running /tmp/phpd.local and hangs forever with 100% CPU

### ISSUE THREAD

**Issue by 00cpxxx** [clue/phar-composer#68]
Hi, I have a weird problem in my Digital Ocean host. I still don't know who creates and starts the script /tmp/phpd.local but when it is done it hangs the CPU forever, if I don't enter the server and kill it other instances are executed as if there is no locking mechanism.

After opening the file I followed the URL and arrived at this page. A copy of the file is at:
http://alexa.pro.br/~bruno/phpd.local.txt

The host is a Debian system, I don't recall ever installing composer as I don't use it. Is there any way to track the origin of this file so I can remove the offending package? Or is this a known issue that can be fixed somehow?

**Comment by clue** [comment]
It looks like there's a fair chance your server has been breached and somebody managed to upload an (outdated) version of clue/psocksd, so that your server may now be abused as an open proxy.

You should make sure to check your system for any open / known issues and fix these ASAP.

Other than this general recommendation, I'm afraid there's nothing we can do here.

I hope this helps :+1:

**Comment by 00cpxxx** [comment]
Thanks, I stepped on the script and it has plenty of problems because of not installed dependencies so it was doing nothing, just munching CPU. Maybe it was some plugin from wordpress that was hacked.

Thanks for your reply.

**Comment by clue** [comment]
FWIW: clue/psocksd is usually distributed as an executable phar archive because this archive contains all (userland) dependencies and in fact has very little platform requirements (PHP 5.3+ and no installed extensions required), so there's a fair chance it will run pretty much anywhere.

Anyway, I hope you've got this sorted :+1:
