### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [clue/phar-composer#80]
Hi, is this project still maintained or are you looking for maintainers?

**Comment by chriskonnertz** [comment]
Obivously no longer maintained...

**Comment by hopeseekr** [comment]
My company can fork it. I use it all the time. We have had considerable success with other abandoned projects, like ccampbell/chromephp. Let me know.

**Comment by hopeseekr** [comment]
I've forked it. Using it as part of the Bettergist Collective. I'll open source it as soon as I've released the Bettergist Collective.

**Comment by clue** [comment]
Thank you for your interest!

This project *is* alive and will receive some updates in the future, but I've had to postpone most of these plans due to lack of focus time due to lack of time/funds. Right now, I can only tell you that I am planning to pick this up again as soon as time permits. If you need this for a commercial project and want to sponsor some features, feel free to reach out :+1:

**Comment by clue** [comment]
I've picked up development again, reach out if you want to help sponsor some features :shipit: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by clue** [comment]
I'd also like to inform you I've just set up a quick roadmap towards a future v2.0.0 release in #88 

I'm also still looking for volunteers and/or maintainers to help with this vision, so let's also ping @staabm, @hopeseekr and others who have previously contributed some great additions to this project :+1:
